config/routes.rb
Rails.application.routes.draw do

  root "products#index"
  get 'carts/show'
  post 'carts/add_product'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :carts_products
  has_many :products, through: :carts_products
end

app/models/carts_product.rb
class CartsProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def get_product_price_with_discount
    (get_product_price - ::Carts::GetProductDiscount.execute(cart_product: self)).round(2)
  end

  def get_product_price
    (self.product.price * self.quantity).round(2)
  end

  def show_product_price?
    get_product_price != get_product_price_with_discount
  end

  def has_offers?
    self.product.offers.where(discount_type: ::Offer::DISCOUNT_TYPES).any?
  end


end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :offers_products
  has_many :products, through: :offers_products

  DISCOUNT_TYPES = %w[BOGO BULK PRODUCT_ADDICT]
end

app/models/offers_product.rb
class OffersProduct < ApplicationRecord
  belongs_to :offer
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :carts_products
  has_many :products, through: :carts_products
  has_many :offers_products
  has_many :offers, through: :offers_products

  validates :name, :price, presence: true
  validates :code, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_cart

  def initialize_cart
    @cart = ::Carts::Initialize.execute(cart_id: session[:cart_id], session: session)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @carts_products = @cart.carts_products
    @total_price = ::Carts::GetTotalPrice.execute(carts_products: @carts_products)
    @total_discount = ::Carts::GetTotalDiscount.execute(carts_products: @carts_products)
  end

  def add_product
    cart = ::Carts::AddAndRemoveProduct.execute(product_id: params[:id], quantity: params[:quantity], cart: @cart)
    total_price = ::Carts::GetTotalPrice.execute(carts_products: cart.carts_products)
    total_discount = ::Carts::GetTotalDiscount.execute(carts_products: cart.carts_products)

    number_products_cart = cart.carts_products.sum(:quantity)
    respond_to do |format|
      format.turbo_stream do
        if params[:product_added_from_cart] == 'true'
          render turbo_stream: [
            turbo_stream.replace("number_products_cart", partial: 'carts/number_products_cart',
                                 locals: { number_products_cart: number_products_cart,
                                           open_modal: false}),
            turbo_stream.replace("products_cart_modal", partial: 'carts/products_cart_modal',
                                 locals: { carts_products: cart.carts_products,
                                           total_price: total_price,
                                           total_discount: total_discount, open_modal: false})
          ]
        else
          render turbo_stream: turbo_stream.replace("number_products_cart", partial: 'carts/number_products_cart',
                                 locals: { number_products_cart: number_products_cart,
                                           open_modal: false})
        end
      end
    end

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_number_products_cart.html.erb
<div id="number_products_cart">
  <p class="flex h-2 w-2 items-center justify-center rounded-full bg-red-500 p-3 text-xs text-white">
    <%= number_products_cart %>
  </p>
</div>

app/views/carts/_product_card.html.erb
<div class="rounded-lg shadow-md">
  <div class="justify-between mb-6 rounded-lg bg-white p-6 shadow-md sm:flex sm:justify-start">
    <div class="sm:ml-4 sm:flex sm:w-full sm:justify-between">
      <div class="sm:mt-0 mr-2">
        <h2 class="text-lg font-bold text-gray-900"><%= carts_product.product.name %></h2>
      </div>
      <div class="mt-4 flex justify-between sm:space-y-6 sm:mt-0 sm:block sm:space-x-6">
        <div class="flex items-center border-gray-100">
          <%= link_to '-', carts_add_product_path(id: carts_product.product.id,
                                                  quantity: carts_product.quantity - 1,
                                                  product_added_from_cart: true),
                                                  data: { turbo_method: :post },
                                                  class: "cursor-pointer rounded-l bg-gray-100 py-1 px-3.5 duration-100 hover:bg-blue-500 hover:text-blue-50" %>
            <input class="h-8 w-10 border bg-white text-center text-xs outline-none" type="number" value="<%= carts_product.quantity %>" min="1" />
          <%= link_to '+', carts_add_product_path(id: carts_product.product.id,
                                                  quantity: carts_product.quantity + 1,
                                                  product_added_from_cart: true),
                                                  data: { turbo_method: :post },
                                                  class: "cursor-pointer rounded-r bg-gray-100 py-1 px-3 duration-100 hover:bg-blue-500 hover:text-blue-50" %>
          <div class="flex-col">

            <% if carts_product.has_offers? %>
              <div class="flex items-center ml-4">
                <p class="text-sm"><%= format('%.2f', carts_product.get_product_price_with_discount) %></p><p class="text-sm">€</p>
              </div>
              <% if carts_product.show_product_price? %>
                <div class="flex right-0 ml-4">
                  <p class="text-xs line-through"><%= format('%.2f', carts_product.get_product_price) %></p><p class="text-sm">€</p>
                </div>
              <% end %>
            <% else %>
              <div class="flex items-center ml-4">
                <p class="text-sm"><%= format('%.2f', carts_product.get_product_price) %></p><p class="text-sm">€</p>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/_products_cart_modal.html.erb
<%= turbo_frame_tag "products_cart_modal" do %>
  <div data-controller="carts--modal">
    <div data-carts--modal-target="sidebarBg" data-action="click->carts--modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <div data-carts--modal-target="sidebar" class="bg-gray-100 fixed top-0 right-0 z-20 w-full sm:w-3/6 lg:w-2/6 h-full overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 <%= 'translate-x-full' if open_modal %>">
      <div data-action="click->carts--modal#close" class="flex items-center space-x-4">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-8 w-8 cursor-pointer duration-150 hover:text-red-500">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </div>
      <h1 class="mb-10 text-center text-2xl font-bold">Your shopping cart</h1>
      <div class="max-w-full justify-center px-6">

        <%= render partial: "product_card", collection: carts_products, as: :carts_product %>

        <div class="mt-6 rounded-lg border bg-white p-6 shadow-md md:mt-0">
          <div class="mb-2 flex justify-between">
            <p class="text-gray-700">Subtotal</p>
            <div class="flex">
              <p class="text-gray-700"><%= format('%.2f', total_price.round(2)) %></p><p>€</p>
            </div>
          </div>
          <div class="flex justify-between">
            <p class="text-gray-700">Discount</p>
            <div class="flex">
              <p class="font-bold text-red-700"><%= format('%.2f', total_discount.round(2)) %></p><p class="line-through text-red-700">€</p>
            </div>
          </div>
          <hr class="my-4" />
          <div class="flex justify-between">
            <p class="text-lg font-bold">Total</p>
            <div class="flex">
              <p class="mb-1 text-lg font-bold"><%= format('%.2f', (total_price - total_discount).round(2)) %></p><p class="mb-1 text-lg font-bold">€</p>
            </div>
          </div>
          <button class="mt-6 w-full rounded-md bg-blue-500 py-1.5 font-medium text-blue-50 hover:bg-blue-600">Buy</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<%= render partial: "products_cart_modal", locals: { carts_products: @carts_products,
                                                     total_price: @total_price,
                                                     total_discount: @total_discount,
                                                     open_modal: true } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmenitizChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <%= render 'shared/header' %>
    <main class="container mx-auto mt-10 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_product.html.erb
<article class="product-<%= product.id %> rounded-xl bg-white p-3 shadow-lg hover:shadow-xl hover:transform hover:scale-105 duration-300 ">
  <div class="mt-1 p-2">
    <h2 class="product-name text-slate-700"><%= product.name %></h2>
    <div class="mt-3 flex items-end justify-between">
      <div class="text-lg font-bold text-blue-500">
        <span class="product-price"><%= format('%.2f', product.price) %></span><span class="money-symbol mr-0">€</span>
      </div>
      <div class="flex items-center space-x-1.5 rounded-lg bg-blue-500 px-4 py-1.5 text-white duration-100 hover:bg-blue-600">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-4 w-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" />
        </svg>
        <%= link_to 'Add to cart', carts_add_product_path(id: product.id, product_added_from_cart: false), data: { turbo_method: :post }, class: "text-sm" %>
      </div>
    </div>
  </div>
</article>

app/views/products/index.html.erb
<%= turbo_frame_tag "products_cart_modal" %>

<section class="products">
  <div class="mx-auto grid max-w-full  grid-cols-1 gap-6 p-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <%= render partial: 'product', collection: @products %>
  </div>
</section>

app/views/shared/_header.html.erb
<div class="antialiased bg-gray-100 dark-mode:bg-gray-900">
  <div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
    <div class="flex max-w-screen-xl px-4 mx-auto items-center justify-between px-6 lg:px-8">
      <div class="items-center justify-between p-4">
        <a class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline" target="_blank">Amenitiz</a>
      </div>

      <%= link_to carts_show_path, data: { turbo_frame: "products_cart_modal" } do  %>
        <div class="relative p-4">
          <div class="t-0 absolute left-3">
            <%= render partial: 'carts/number_products_cart', locals: { number_products_cart: @cart.carts_products.sum(:quantity) } %>
          </div>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="file: mt-4 h-6 w-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"></path>
          </svg>
        </div>
      <% end %>

    </div>
  </div>
</div>